---
title: Code Llama, a state-of-the-art large language model for coding
author: Danh Thien Luu (79663)
toc: true
toc-own-page: true
numbersections: true
geometry: "left=3cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
papersize: a4
lang: de-DE
fontsize: 12pt
indent: true
csl: acm.csl
bibliography: zotero.bib
link-citations: true
---

